name: Auto Tag Release

on:
  push:
    branches: [main]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          version=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          custom_tag: "v${{ steps.get_version.outputs.version }}"
